add models
M1RRoN/GSpot pull request #1
Opened 2023-03-21 06:59 UTC by M1RRoN

2023-03-21 07:26 UTC, egorFilippo requested changes

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/managers.py
> +        return self.get_queryset().with_workers_count()
```suggestion
class CompanyManager(models.Manager):
    def get_queryset(self):
        return (
                        super().get_queryset()
                        .annotate(workers_count=Coalesce(Count('username'), 0))
        )
```

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    avatar = models.ImageField(blank=True, upload_to='backend/users/backend/static/img/%Y/%m/%d')
Точно не в static. Можно без upload_to прописывать. Пока что не выбрали место хранения. Будет лежать в корне media.

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    email = models.EmailField(unique=True)
Эти поля вроде бы были в BaseUser

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
Это поле в BaseUser

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    objects = CompanyManager()
CompanyManager - менеджер модельки компании, а не пользователя компании. CompanyUserManager

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +class DeveloperFriends(models.Model):
```suggestion
class CompanyUserFriends(models.Model):
```

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    user2 = models.ForeignKey(CompanyUser, on_delete=models.CASCADE, related_name='user2_friends')
Нужно обсудить определение друзей.
1. Как определить, кто подал заявку?
2. Если отклонили заявку в друзья, делаем ли подписчиков из этой заявки?

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    image = models.ImageField(blank=True, upload_to='backend/users/backend/static/img/%Y/%m/%d')
тоже не static

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    email = models.EmailField(max_length=50, unique=True)
тут не надо указывать длину. Почта может быть до 255 символов

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    id = models.IntegerField(primary_key=True)
это в базовой модели джанги есть. Можно не делать поле id

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +    icon = models.ImageField(blank=True, upload_to='backend/users/backend/static/icon')
upload убрать

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +class ContentType(models.Model):
Все права сделать по образу и подобию https://github.com/DJWOMS/GSpot/pull/28

2023-03-21 07:26 UTC, egorFilippo commented on backend/users/backend/developers/tests/test_manager.py
> +            print(company['id'], company['name'], company['workers_count'])
Тесты обычно не принтят, а assert делают. Такой тест никогда не падёт с ошибкой.

2023-03-21 11:32 UTC, kalinavladd commented on backend/users/backend/developers/managers.py
> -    def with_workers_count(self):
первый вариант правильный, посмотри в доке также работу с аннотациями и с Count. https://docs.djangoproject.com/en/4.1/topics/db/aggregation/#cheat-sheet

2023-03-21 11:32 UTC, kalinavladd commented on backend/users/backend/developers/managers.py
> -    def with_workers_count(self):
Я тебе давал ссылку на документацию

2023-03-21 11:32 UTC, kalinavladd commented on backend/users/backend/developers/managers.py
> -    def get_workers_count(self):
А тут метод не нужен, тебе пока нужен именно кверисет метод. Вызывать ты его будешь CompanyUser.objects.filter(что-то тут).with_workers_count(). и вот такую конструкцию тебе надо протестить, посмотреть возвращается ли твое поле и правильный ли ответ

2023-03-21 11:32 UTC, kalinavladd commented on backend/users/backend/developers/tests/test_manager.py
>          self.user1 = CompanyUser.objects.create(
https://factoryboy.readthedocs.io/en/stable/, напиши себе фабрики для тестов, они в дальнейшем будут экономить тебе время и количество кода.

2023-03-21 11:32 UTC, kalinavladd commented on backend/users/backend/developers/tests/test_manager.py
>          self.user1 = CompanyUser.objects.create(
Вчера говорили протестировать модели прав которые вы пишите, методы has_perm, has_perms хотя бы

2023-03-21 11:32 UTC, kalinavladd commented on backend/users/backend/developers/managers.py
> -    def get_workers_count(self):
Также добавь метод available_workers_for_company. У тебя в реквесте будет приходить компания, ты должен будешь отдавать компании её сотрудников, а не чужих, соответственно твой метод должен принимать на вход айдишник. И структура уже для этой таски будет такая как ты сразу писал, available_workers_for_company в CompanyQuerySet и def available_workers_for_company в CompanyManager которая делает return self.get_queryset(). available_workers_for_company.

И у тебя уже будет тестироваться логика, ты создашь несколько компаний, и несколько сотрудников к каждой компании. и юзать Company.obj. available_workers_for_company(id=company) первый кейс (сверяешь правильные ли юзеры тебе вернулись, второй кейс Company.obj. available_workers_for_company(id=company).with_count() сверяешь правильное ли у всех количество юзеров

2023-03-22 03:53 UTC, egorFilippo commented on backend/users/backend/developers/managers.py
> -    def with_workers_count(self):
Влад, вероятно, вот так предлагает реализовать. С таким подходом я согласен)

https://docs.djangoproject.com/en/4.1/topics/db/managers/#custom-managers

2023-03-22 10:00 UTC, kalinavladd approved these changes

2023-03-22 10:03 UTC, merged