add developers views
M1RRoN/GSpot pull request #3
Opened 2023-04-15 09:45 UTC by M1RRoN

2023-04-15 11:16 UTC, egorFilippo requested changes

2023-04-15 11:16 UTC, egorFilippo commented on backend/users/backend/developers/tests/test_serializers.py
> +        # self.assertEqual(serializer.data, self.serializer_data)
Убрать, если не нужно

2023-04-15 11:16 UTC, egorFilippo commented on backend/users/backend/developers/serializers.py
> +        model = Company
По логике названия моделька должна быть CompanyEmployee
Или я чего-то не понял?

2023-04-15 11:16 UTC, egorFilippo commented on backend/users/backend/developers/urls.py
> +router.register(r'company_employee', views.CompanyEmployeeViewSet, basename='company_employee')
Я думаю обозначение строки как регулярку можно убрать "r"

Думаю, что лучше делать `company-employee'. А в идеале 'company/<int:pk>/employees'

2023-04-15 11:16 UTC, egorFilippo commented on backend/users/backend/developers/serializers.py
> +        fields = '__all__'
Вообще я бы предложил сделать сериалайзер компании, который будет показывать все поля. От него наследовать сериалайзеры с более говорящими названиями "CompanyForOwnerSerializer". И в эти сериалайзерах прописывать поля, сразу добавляя их в readonly_fields (какие требуется).

Сейчас названия не говорят о назначении.

2023-04-15 11:16 UTC, egorFilippo commented on backend/users/backend/developers/views.py
> +class CompanyRetrieveUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
Я бы сделал 1 ViewSet, в который бы зашил всю логику. 

Сериалайзеры можно менять в методе get_serializer_class, вместо нескольких вьюх. Ну и прочая валидация в одном классе нормально помещается. Почему бы не использовать ModelViewSet?

2023-04-23 10:06 UTC, mozambique-ya reviewed
1) название PR не по формату
2) нет описания PR - что ты делал приходится догадываться по коду

В остальном вижу тесты, вижу комменты к тестам - это зачет.

2023-04-23 10:06 UTC, mozambique-ya commented on backend/users/backend/developers/tests/test_views.py
> +        self.companyuser3 = CompanyUser.objects.create(username='companyuser3', password='password123123213', email='user1232@123.ru')
про генерацию моделей для тестов вчера говорил на мите )

2023-04-23 10:06 UTC, mozambique-ya commented on backend/users/backend/developers/tests/test_views.py
> +        """Список компаний для superuser должен возвращать все компании."""
зачет за пояснения )

2023-04-23 11:06 UTC, mozambique-ya commented
принимаю PR, есть хорошие реализации функционала. Но в будущем очень много будем исправлять.

2023-04-23 11:07 UTC, mozambique-ya approved these changes

2023-04-23 15:04 UTC, merged